CREATE TABLE PASIIEN (
  2  KD_PASIEN CHAR(5) PRIMARY KEY NOT NULL,
  3  NAMA_PASIEN VARCHAR(35) NOT NULL,
  4  ALAMAT_PASIEN VARCHAR(40) NOT NULL,
  5  NOHP_PASIEN NUMBER NOT NULL);

create table DOKTER (
  2  KD_DOKTER CHAR(5) PRIMARY KEY NOT NULL,
  3  NAMA_DOKTER VARCHAR(35) NOT NULL,
  4  NOHP_DOKTER NUMBER NOT NULL,
  5  SPESIALIS VARCHAR(35) NOT NULL);

create table PERAWAT (
  2  KD_PERAWAT CHAR(5) NOT NULL,
  3  KD_DOKTER CHAR(5) NOT NULL,
  4  NAMA_PERAWAT VARCHAR(35) NOT NULL,
  5  NOHP_PERAWAT NUMBER NOT NULL,
  6  PRIMARY KEY (KD_PERAWAT, KD_DOKTER),
  7  FOREIGN KEY (KD_DOKTER) REFERENCES dokter (KD_DOKTER));

CREATE TABLE KAMAR (
  2  KD_KAMAR CHAR(5) PRIMARY KEY NOT NULL,
  3  NAMA_KAMAR VARCHAR(25) NOT NULL,
  4  JENIS_KAMAR VARCHAR(20) NOT NULL);

CREATE TABLE PEMBAYARAN (
  2  KD_PEMBAYARAN CHAR(5) NOT NULL,
  3  KD_PASIEN CHAR(5) NOT NULL,
  4  JUMLAH_PEMBAYARAN NUMBER NOT NULL,
  5  PRIMARY KEY(KD_PEMBAYARAN, KD_PASIEN),
  6  FOREIGN KEY (KD_PASIEN) REFERENCES PASIIEN (KD_PASIEN));

  CREATE TABLE OBAT (
  2  KD_OBAT CHAR (5) NOT NULL,
  3  KD_DOKTER CHAR (5) NOT NULL,
  4  KD_PASIEN CHAR (5) NOT NULL,
  5  NAMA_OBAT VARCHAR(20) NOT NULL,
  6  JENIS_OBAT VARCHAR(20) NOT NULL,
  7  HARGA_OBAT NUMBER NOT NULL,
  8  PRIMARY KEY (KD_OBAT, KD_DOKTER, KD_PASIEN),
  9  FOREIGN KEY (KD_DOKTER) REFERENCES DOKTER (KD_DOKTER),
 10  FOREIGN KEY (KD_PASIEN) REFERENCES PASIIEN (KD_PASIEN));

CREATE TABLE PERIKSA (
  2  KD_PASIEN CHAR (5) NOT NULL,
  3  KD_DOKTER CHAR (5) NOT NULL,
  4  PENYAKIT VARCHAR (25) NOT NULL,
  5  TGL_PERIKSA DATE NOT NULL,
  6  PRIMARY KEY (KD_PASIEN, KD_DOKTER),
  7  FOREIGN KEY (KD_PASIEN) REFERENCES PASIIEN (KD_PASIEN),
  8  FOREIGN KEY (KD_DOKTER) REFERENCES DOKTER (KD_DOKTER));
